### ISSUE TITLE
Undefined in node add/edit form

### ISSUE THREAD

**Issue by tolesolo** [signalpoint/DrupalGap#639]
![error6](https://cloud.githubusercontent.com/assets/14232358/10177062/52b8f91c-6722-11e5-968c-74239c70409b.jpg)

appear in custom content type only
Not appear in default content type like basic page and article

What I've done:
- I have changed label of the title
- Automatic node title module installed

Yeah, I can make it hidden with css, but I currious... none error log messages

**Comment by signalpoint** [comment]
@tolesolo I believe this issue has been fixed, and should be available in the latest `bin/drupalgap.js` file.

**Comment by tolesolo** [comment]
@signalpoint Hi Tyler, thank you for your reply. My drupalgap was updated with the latest drupalgap.js and form.elements.inc.js , but still appear that undefined in the form

did you forget to update the index.html, cordova.index.html and default.index.html to load the favicon.ico
<code>
    
    

```
<!-- Touch Icons - iOS and Android 2.1+ 180x180 pixels in size. --> 
<link rel="apple-touch-icon-precomposed" href="favicon.ico">

<!-- Firefox, Chrome, Safari, IE 11+ and Opera. 196x196 pixels in size. -->
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
```

</code>

**Comment by signalpoint** [comment]
@tolesolo You only need the `bin/drupalgap.js` file, because all the files in the `src/`directory are not used to run the app. Read about the makefile here to understand more: http://drupalgap.org/node/224

The favicon should be a separate issue.

**Comment by tolesolo** [comment]
I'm sorry, yes, the favicon is a separate issue

**Comment by g33kyg1rl** [comment]
I am still experiencing this issue even after updating the `bin/drupalgap.js` with the latest version. Is there any information I can provide to help resolve this issue?

**Comment by signalpoint** [comment]
This one happens to me once in a while, usually with a missing field, or some type of contributed field. A report (field name, type, widget, module) of the fields in use on the content type, as well as their order on the "manage fields" page. Otherwise, setting a break point in your web developer tools and tracing through the render of the form, is a great way to go.

**Comment by g33kyg1rl** [comment]
I am using the Title module. Here is a screenshot of the content type mange fields section.
![14-33-15](https://cloud.githubusercontent.com/assets/18540479/14691255/167915d0-0705-11e6-970d-aff02e900246.png)

Here is the undefined text showing up. I know it has to do with the Title module because when I disable the title module, the text goes away.
![create check-in 2016-04-20 14-34-38](https://cloud.githubusercontent.com/assets/18540479/14691277/34130c9a-0705-11e6-8c66-ccccef17cbfa.png)

> Otherwise, setting a break point in your web developer tools and tracing through the render of the form, is a great way to go.

I am not sure what that means, you wouldn't happen to have a tutorial, would you? :) ;)

**Comment by signalpoint** [comment]
@g33kyg1rl thank you for the screen shots, that is very helpful. Does your console log say anything/warnings?
