### ISSUE TITLE
Multiple Taxonomy Term Reference Fields on a Node Edit Form

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#660]
I have a node type that uses 2 term reference fields. When I click to create a new node in the app, I get an error message that the fields are required ... even though I entered terms into the field. It does not appear to be limited to the **autocomplete** widget because I get the same error if I use **select list** as well.

I don't see any error messages in console log.

![tag-fields](https://cloud.githubusercontent.com/assets/13283396/11052440/27aa4588-8715-11e5-912a-325be860ac8c.PNG)

![term-field](https://cloud.githubusercontent.com/assets/13283396/11052450/3bedae0e-8715-11e5-918a-735803036fad.PNG)

![save-error](https://cloud.githubusercontent.com/assets/13283396/11052451/3fe0e490-8715-11e5-92f0-fe71fff7a5f8.PNG)

**Comment by mkinnan** [comment]
When I view (or attempt to edit) a node in the app that was saved via the website, I get the following error messages:

`Notice: Undefined index: target_type in drupalgap_entityreference_services_request_postprocess_alter() (line 39 of /var/www/html/sites/all/modules/drupalgap/modules/drupalgap_entityreference/drupalgap_entityreference.module).`
`Notice: Undefined index: target_id in drupalgap_entityreference_services_request_postprocess_alter() (line 50 of /var/www/html/sites/all/modules/drupalgap/modules/drupalgap_entityreference/drupalgap_entityreference.module).`

**Comment by signalpoint** [comment]
@mkinnan I believe this is happening because I seem to recall shamelessly programming in the ability to only edit one taxonomy term reference field per content type (aka entity bundle). Essentially DG is only smart enough to handle one taxonomy term reference field on a form at a time. The quickest way around this is to use Entity reference fields instead, which have much better support within DG. Otherwise, DG needs to be abstracted a bit to allow for multiple taxonomy term reference fields on a form at a time.

**Comment by mkinnan** [comment]
@signalpoint Thanks for clarifying. I will give entity reference fields a try.

**Comment by mkinnan** [comment]
I am still getting the same errors ... here is what my content type looks like:

![content-fields](https://cloud.githubusercontent.com/assets/13283396/11385885/58ccc336-92da-11e5-84f5-b3407591308f.PNG)
I am running Drupal-7.x-41, Drupalgap-7.x-14, Entity API 7.x-1.6, Entity Reference 7.x-1.1.

**Comment by mkinnan** [comment]
And also Services 7.x-3.12 (patched)

**Comment by signalpoint** [comment]
@mkinnan I'd recommend stepping through `drupalgap_entityreference.module` and using watchdog/print_r/dpm/etc to see what field(s) is failing to load its target_type setting.

http://cgit.drupalcode.org/drupalgap/tree/modules/drupalgap_entityreference/drupalgap_entityreference.module#n37

**Comment by mkinnan** [comment]
Using the latest drupalgap code today, I don't get those errors now ... but I now see this in console log when I try to type in a few letters in the entity reference field:

`
GET http://example.com/?q=drupalgap/taxonomy_term.json&fields=tid,name&param…=group_keywords&parameters_op[name]=like&options[parameters_op][name]=like 406 (Not Acceptable : Invalid query provided, double check that the fields and parameters you defined are correct and exist. SQLSTATE[42703]: Undefined column: 7 ERROR:  column "type" does not existLINE 5: WHERE  (name::text ILIKE '%auto%') AND (type IN  ('group_key...    
`

I am still using the same fields from the image a couple posts up ... one entity reference field for a taxonomy term vocabulary.

**Comment by mkinnan** [comment]
I edited my comment above ... I get that query error when I start typing any letters into the entity reference field box, not when I save the node.

**Comment by signalpoint** [comment]
@mkinnan I'd recommend upgrading to the latest dev version of the Services module (because my patch got rolled in, so we no longer need the patch). Also upgrade to the latest version of jDrupal. That should fix the SQL error.

**Comment by mkinnan** [comment]
Upgrade services module to dev ... downloaded the latest jdrupal from here:
https://raw.githubusercontent.com/easystreet3/jDrupal/7.x-1.x/bin/jdrupal.js

updated index.html to reflect jdrupal.js file

flushed browser and website cache ... 

Still getting the query error.

**Comment by mkinnan** [comment]
Created a new Drupal site from scratch ... downloaded latest jdrupal ... configured index.html to reflect jdrupal file ... still getting the errors ... when I have an entity reference field.

![capture](https://cloud.githubusercontent.com/assets/13283396/11706976/6bfbace6-9ebb-11e5-9d53-5a26dd6c2ac4.PNG)

I don't know what else to do ...

**Comment by mkinnan** [comment]
Still no luck getting any of this to work ... has anyone success fully gotten entity reference to work in an app?

**Comment by mkinnan** [comment]
Here is the full query that is causing the failure that I copied from the my PSQL error logs:

```
SELECT tth.*, t.tid AS tid, t.name AS name FROM 
taxonomy_term_data t
INNER JOIN taxonomy_term_hierarchy tth ON t.tid = tth.tid
WHERE  (name::text ILIKE '%New York%') AND (type IN  ('locations')) 
LIMIT 20 OFFSET 0
```

I have no idea where it is being assembled from, but there is no column **type** in either of those tables. The _type_ should be a vocabulary ID field.

**Comment by mkinnan** [comment]
Where does this URL get formed:

```
http://example.com/?q=drupalgap/taxonomy_term.json&fields=tid,name&parameters[name]=%25auto%25&parameters[type]=group_keywords&parameters_op[name]=like&options[parameters_op][name]=like
```

I did a find in file for 'taxonomy_term.json' but got no hits in the drupalgap code. That url seems like the culprit. If the **[type]=group_keywords** is removed, then no bugs ... just don't know where the URL is getting assembled.

**Comment by mkinnan** [comment]
Replacing **[type]=group_keywords** with something like **[vid]=2**, and the the url returns correct results with no error. Just don't know where to find where that URL is assembled.

**Comment by signalpoint** [comment]
This is probably the spot where the query is assembled: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/taxonomy/taxonomy.js#L164

It's very odd that the group_keywords query string parameter is present, I have no idea where that is coming from.

**Comment by mkinnan** [comment]
The group_keywords parameter is the name of the entity reference field for a specific taxonomy term vocabulary. 

<div>-------- Original message --------</div><div>From: Tyler Frankenstein notifications@github.com </div><div>Date:01/10/2016  2:37 PM  (GMT-07:00) </div><div>To: signalpoint/DrupalGap DrupalGap@noreply.github.com </div><div>Cc: mkinnan mark@saponico.com </div><div>Subject: Re: [DrupalGap] Multiple Taxonomy Term Reference Fields on a Node Edit Form (#660) </div><div>
</div>This is probably the spot where the query is assembled: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/taxonomy/taxonomy.js#L164

It's very odd that the group_keywords query string parameter is present, I have no idea where that is coming from.

**Comment by mkinnan** [comment]
First, I did a console.log on 'query' for the function **entity_index_build_query_string(query)** in jdrupal.js. That function is receiving the 'type' parameter. So, continued going backwards.

Next, I did a console.log on 'query' for the function **entity_index(entity_type, query, options)** which calls **entity_index_build_query_string(query)**. **entity_index** is still receiving parameter type via query. entity_type does yield _taxonomny_term_ which is correct.

Next, the function **taxonomy_term_index(query, options)** calls **entity_index('taxonomy_term', query, options)** ... and query still has '_type_' parameter as '_group_keywords_'.

There are 3 funcions in drupalgap.js that call the **taxonomy_term_index** function, but none of them are being called for the entity_reference field (referencing a taxonomy term vocabulary)... since console.log is returning nothing for me. However, if I type text into an autocomlete term reference field, the fields trigger and I see that via console.log.

It appears a different function is being called that may not be related to the taxonomy.js functions ... just haven't been able to find it. So, stuck again.

**Comment by signalpoint** [comment]
@mkinnan So your field is an entity reference field (referencing a taxonomy vocabulary), or a taxonomy term reference field? If it's the latter, it should trigger the console.log messages you described. If it's the aforementioned then it'd run through the DrupalGap entityreference module.

If you need to get rid of the group_keywords, you can probably use this hook:

http://api.drupalgap.org/global.html#hook_services_preprocess

That should allow you to modify the `query` object, and if not at the very minimum you should be able to modify the `options` object to remove the offender from the URL query string.

**Comment by mkinnan** [comment]
Yes, I am using an entity reference field (referencing a taxonomy vocabulary),

I have looked at the Drupalgap entityreference module, but don't see where (or referencing another function) the URL query is getting generated except in the **taxonomy_term_index** functions in _drupalgap.js_:

```
    var query = {
      fields: ['tid', 'name'],
      parameters: {
        vid: vid,
        name: '%' + value + '%'
      },
      parameters_op: {
        name: 'like'
      }
    };
```

But none of the taxonomy_index_term functions are getting triggered for the entity reference field. But they should, since the referenced entity is a taxonomy vocabulary, right?

I can't just remove **parameters[type]=group_keywords** via hook_services_preprocess from the query object. I would also have to add the vocabulary ID (vid) parameter and a value.

I am wondering if the entity reference fields referencing taxonomy vocabularies are referencing _nodes_ instead of _terms_.

**Comment by mkinnan** [comment]
So **parameters[type]=group_keywords** is the name for the _vocabulary_.

Still trying to trace this backwards. It appears the function **taxonomy_term_index** is being called by `_theme_autocomplete(list, e, data, autocomplete_id)` in _drupalgap.js_. There is some code in that function that appears to deal with assembling parameters. Not sure that is the right place, but that's where I will be looking next when I have time.

**Comment by mkinnan** [comment]
Could `_theme_autocomplete(list, e, data, autocomplete_id)` in _drupalgap.js_ be the issue? Look in that function at `case: 'base'`. A `console.log(autocomplete_id)` returns the name of my field **field_term_group_keywords** and `console.log(field_settings.handler_settings.target_bundles)` is giving the **group_keywords** value. `console.log(options.parameters.type)` also gives **group_keywords** value.

Thoughts?

**Comment by mkinnan** [comment]
In the function `_theme_autocomplete(list, e, data, autocomplete_id)` for case: 'base' in _drupalgap.js_, I replaced

```
            options.parameters.type = bundle;
```

with

```
          if (field_settings.target_type = 'taxonomy_term') {
            options.parameters.vid = 4; // don't know if there is a function to get vid from vocab machine name
          } else {
            options.parameters.type = bundle;
          }
```

then the error message no longer happens in console.log and the URL string is now

`http://example.com/?q=drupalgap/taxonomy_term.json&fields=tid,name&parameters[name]=%25auto%25&parameters[vid]=2&parameters_op[name]=like&options[parameters_op][name]=like`

However, the entity reference fields (taxonomy term reference or user reference) just don't work at all for me even with the error message fixed.

**Comment by mkinnan** [comment]
I can't get the entity reference drupalgap module to work for nodes, terms, or users. Are there any plans to get it working?

**Comment by signalpoint** [comment]
@mkinnan This should now be fixed thanks to your sponsored development:
- http://cgit.drupalcode.org/drupalgap/commit/?id=55e0b76
- https://github.com/signalpoint/DrupalGap/commit/f364caa903d16461fcecc37eee64b287c248f853

When using an autocomplete, I believe users need to actually click on the autocomplete result to have it be set properly, i.e. they can't just type the complete term into the box, they actually have to click on the term result to trigger the value being set properly.
