### ISSUE TITLE
Contact Form Category Field

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#820]
Category field is showing blank on the Contact form preventing the use of the contact form. Using the latest drupalgap.js.

**Comment by signalpoint** [comment]
Have you enabled the resource under structure services that allows the
retrieval of the categories?
- Tyler (sent from mobile device)

**Comment by mkinnan** [comment]
I don't see a service for categories for contact forms.

Every single box on the services list is checked.

**Comment by mkinnan** [comment]
Trying a work around, but upon submit still tells me "Category field required"

```
if (form.id == 'contact_site_form') {
  form.elements['cid'].default_value = '1';
  form.elements['cid'].access = true;
  form.elements['cid'].prefix = '<div style="display: none;">';
  form.elements['cid'].suffix = '</div>';
}
```

Thoughts?

**Comment by signalpoint** [comment]
@mkinnan The resource I was thinking of was the `index` resource located under `contact` at admin/structure/services/list/drupalgap/resources - sounds like you already have that checked, which is good.

How many categories, and what are their ids, listed at this page in Drupal? `admin/structure/contact`

**Comment by mkinnan** [comment]
There is only 1 category:

![contact](https://cloud.githubusercontent.com/assets/13283396/16788119/4000fd6e-485f-11e6-9e48-56e03d485864.PNG)

**Comment by signalpoint** [comment]
@mkinnan What JSON data do you get when you go to `?q=drupalgap/contact.json` ?

**Comment by mkinnan** [comment]
It's giving a blank screen. No JSON or empty brackets.

**Comment by signalpoint** [comment]
@mkinnan That is the path to the `index` resource, which requires the `access site-wide contact form` permission. Is that permission enabled for your desired user role(s)?

**Comment by mkinnan** [comment]
Using Chrome. Logged into website as user 1. Permissions are set for all users to use contact form. No watchdog logs showing any related errors. Can access `contact` ... but `?q=drupalgap/contact.json` is blank.

**Comment by signalpoint** [comment]
@mkinnan Are you using something other than mysql?

I see that that the `services_contact_categories()` function uses a query that may only work with mysql: http://cgit.drupalcode.org/services_contact/tree/services_contact.resource.inc

No matter what, that function should be updated to use the D7 Database API instead of a hardcoded mysql query (my bad).

**Comment by mkinnan** [comment]
I am using PostgreSQL ..

PSQL does not like brackets `{ }` around table names if i recall correctly.

**Comment by signalpoint** [comment]
@mkinnan Ok, thanks for helping me track this down. I've pushed a new release of the `services_contact` module for Drupal, it should be ready in 15-20 minutes from d.o to get published.

Otherwise you can grab the latest dev snapshot of the module in drupal: `drush dl services_contact --dev`

**Comment by mkinnan** [comment]
This still isn't working for me ... the Category is still not showing up.
- I updated to the latest versions of Services and Services Contact.
- Both modules are enabled.
- All checkboxes on the services page are checked.
- The link contact.json does show the correct JSON now.
- I am using the version of drupalgap.js with the change 'category' to 'cid'.

**Comment by ReisQuarteu** [comment]
Hi.
I'm facing the same problem, but only on the mobile app.
I've done all the steps suggested above. When opening the contact form with the web app, the category field does not appear, nor it prevents the user from submitting the form. Nevertheless, when opening the contact form within the mobile app (compiled to Android), the category field does appear with no options to be selected by my users; moreover, the category filed is mandatory (?!?) and prevents the user from submitting the form.
I'll keep on trying to find a solution for this problem.
Thanks in advance! :)
